CREATE TABLE IF NOT EXISTS USERS (
    RFID VARCHAR(8) PRIMARY KEY,
    NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL,
    BLOCKED INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS READINGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RFID INTEGER,
    DATE_TIME DATETIME,
    VALUE REAL,
    FOREIGN KEY(RFID) REFERENCES USERS(RFID)
);

CREATE TABLE IF NOT EXISTS BOSSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE,
    PASSWORD_HASH TEXT
);

CREATE TABLE IF NOT EXISTS BLOCKADES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    RFID INTEGER,
    START_DATE DATETIME,
    END_DATE DATETIME,
    BLOCKADE_TYPE VARCHAR(10) CHECK(BLOCKADE_TYPE IN ('MANUAL', 'AUTOMATIC')),
    STATUS VARCHAR(10) CHECK(STATUS IN ('ONGOING', 'DONE')),
    FOREIGN KEY(RFID) REFERENCES USERS(RFID)
);
