CREATE TABLE IF NOT EXISTS USERS (
    user_id VARCHAR(8) PRIMARY KEY,
    NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL,
    BLOCKED INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS READINGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id VARCHAR(8),
    DATE_TIME DATETIME,
    VALUE REAL,
    uuid TEXT,
    breathalyzer TEXT,
    FOREIGN KEY(user_id) REFERENCES USERS(user_id)
);

CREATE TABLE IF NOT EXISTS BOSSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE,
    PASSWORD_HASH TEXT
);

CREATE TABLE IF NOT EXISTS BLOCKADES(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id VARCHAR(8),
    START_DATE DATETIME,
    END_DATE DATETIME,
    BLOCKADE_TYPE VARCHAR(10) CHECK(BLOCKADE_TYPE IN ('MANUAL', 'AUTOMATIC')),
    STATUS VARCHAR(10) CHECK(STATUS IN ('ONGOING', 'DONE')),
    FOREIGN KEY(user_id) REFERENCES USERS(user_id)
);

CREATE TABLE IF NOT EXISTS UUIDS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id VARCHAR(8),
    UUID TEXT UNIQUE,
    PHOTO BLOB,
    FOREIGN KEY(user_id) REFERENCES USERS(user_id)
);