CREATE TABLE IF NOT EXISTS USERS (
    RFID TEXT PRIMARY KEY,
    NAME TEXT,
    SURNAME TEXT
);

CREATE TABLE IF NOT EXISTS READINGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FK_RFID TEXT,
    DATE_TIME DATETIME,
    VALUE REAL,
    FOREIGN KEY(FK_RFID) REFERENCES USERS(RFID)
);

CREATE TABLE IF NOT EXISTS BOSSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE,
    PASSWORD_HASH TEXT
);
