CREATE TABLE USERS (
    RFID TEXT PRIMARY KEY,
    NAME TEXT,
    SURNAME TEXT
);

CREATE TABLE READINGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FK_RFID TEXT,
    DATE_TIME DATETIME,
    VALUE REAL,
    FOREIGN KEY(FK_RFID) REFERENCES USERS(RFID)
);