CREATE TABLE IF NOT EXISTS USERS (
    RFID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    SURNAME TEXT NOT NULL,
    BLOCKED INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS READINGS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FK_RFID TEXT,
    DATE_TIME DATETIME,
    VALUE REAL,
    FOREIGN KEY(FK_RFID) REFERENCES USERS(RFID)
);

CREATE TABLE IF NOT EXISTS BOSSES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME TEXT UNIQUE,
    PASSWORD_HASH TEXT
);
