[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 57600
board_build.f_cpu = 16000000L
; Set old bootloader flag
board_upload.maximum_size = 30720
upload_resetmethod = ck
; Can uncomment if needed
; upload_port = /dev/ttyUSB0
lib_deps =
    git+https://github.com/miguel5612/MQSensorsLib.git
    LiquidCrystal_I2C
    Servo
    https://github.com/RobTillaart/UUID.git